#!/bin/bash

# Change directory to your emacs.d if it exists, or create it if it doesn't
if [ -d "$HOME/.emacs.d/themes" ]; then
    cd "$HOME/.emacs.d/themes"
else
    mkdir -p "$HOME/.emacs.d/themes"
    cd "$HOME/.emacs.d/themes"
fi

# Download the theme
wget https://raw.githubusercontent.com/greduan/emacs-theme-gruvbox/master/gruvbox-dark-soft-theme.el

# Append to init.el or .emacs to use the theme, after checking if it exists
if [ -f "$HOME/.emacs.d/init.el" ]; then
    echo "(add-to-list 'custom-theme-load-path \"~/.emacs.d/themes\")" >> "$HOME/.emacs.d/init.el"
    echo "(load-theme 'gruvbox-dark-soft t)" >> "$HOME/.emacs.d/init.el"
else
    # If no configuration file exists, create one
    echo "(add-to-list 'custom-theme-load-path \"~/.emacs.d/themes\")" > "$HOME/.emacs.d/init.el"
    echo "(load-theme 'gruvbox-dark-soft t)" >> "$HOME/.emacs.d/init.el"
fi
