#!/bin/bash

#optional - update to the latest version of emacs - UNTESTED
#if you choose to go down this path you are on your own, this is based off how I was able to update to emacs 28 on my local machine
#add progress message for unofficial repo
#echo "Adding unofficial repo for emacs v28..."
#sudo apt-get update > /dev/null || { echo "Failed to update packages"; exit 1; }
#sudo add-apt-repository -y ppa:kelleyk/emacs > /dev/null || { echo "Failed to add unofficial repo"; exit 1; }

#kill any instances of emacs that are running
#pkill emacs

#remove any existing emacs installations
#sudo apt-get remove --autoremove emacs emacs-common > /dev/null

#install latest version of emacs
#sudo apt-get install emacs28-nox


#Themes

#download theme from repo

#add theme to emacs config file
echo ";;Themes" >> ~/.emacs.d/init.el
echo "(load-theme 'gruvbox-dark-medium t)" >> ~/.emacs.d/init.el
